### ISSUE TITLE
Estimated Time to Release Code

### ISSUE THREAD

**Issue by HenryPengZou** [liangjinggui/ALUP#1]
Dear Authors,

Congratulations on your paper being accepted by NAACL 2024! Do you have an estimated time to release the code? 

Thanks!

**Comment by HenryPengZou** [comment]
Hi @liangjinggui, do you have any plan to release the code?

**Comment by liangjinggui** [comment]
> Hi @liangjinggui, do you have any plan to release the code?

Thank you for your attention! We are finalizing the code and plan to release it soon.
